nameOverride: ""
fullnameOverride: ""
version: v1

studenID: ""

deployment:
  env: []
  replicas: 1

image:
  repository: docker.io/d0ck3rj3ff/caj-fare
  tag: latest
  pullPolicy: Always

route:
  domain: apps.penguin.rhtw.kubedev.org

# Affinity
affinity: {}
  # nodeAffinity:
  #   requiredDuringSchedulingIgnoredDuringExecution:
  #     nodeSelectorTerms:
  #     - matchExpressions:
  #       - key: kubernetes.io/hostname
  #         operator: In
  #         values:
  #         - gke-gke-blr-default-pool-06a23412-0dkt

# Tolerations and Taints
tolerations: []
  # - key: "key1"
  #   operator: "Equal"
  #   value: "value1"
  #   effect: "NoSchedule"
  # - key: "key1"
  #   operator: "Equal"
  #   value: "value1"
  #   effect: "NoExecute"

# Node Selector
nodeSelector: {}

# Extra labels
labels: {}

# Extra annotations 
annotations: {}
